mixed-port: '7890'
proxies:
- cipher: chacha20
  name: 5pel5pys6auY6YCfIDFb5pmu6YCaXQ
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 50120
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5pel5pys6auY6YCfIDJb5pmu6YCaXQ
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 50121
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5pel5pys6auY6YCfIDNb5pmu6YCaXQ
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 50122
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5pel5pys6auY6YCfIDRb5pmu6YCaXQ
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 50123
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5pel5pys6auY6YCfIDVb5pmu6YCaXQ
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 50124
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5pel5pys6auY6YCfIDZb5pmu6YCaXQ
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 50125
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5pel5pys6auY6YCfIDdb5pmu6YCaXQ
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 50126
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5pel5pys6auY6YCfIDhb5pmu6YCaXQ
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 50127
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5pel5pys6auY6YCfIDlb5pmu6YCaXQ
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 50128
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5pel5pys6auY6YCfIDEwW-aZrumAml0
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 50129
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5pel5pys6auY6YCfIDExW-aZrumAml0
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 50130
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5pel5pys6auY6YCfIDEyW-aZrumAml0
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 50131
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5pel5pys6auY6YCfIDEzW-aZrumAml0
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 50132
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5pel5pys6auY6YCfIDE0W-aZrumAml0
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 50133
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5pel5pys6auY6YCfIDE1W-aZrumAml0
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 50134
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5pel5pys6auY6YCfIDE2W-aZrumAml0
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 50135
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5paw5Yqg5Z2h6auY6YCfIDE3W-aZrumAml0
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 50136
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5paw5Yqg5Z2h6auY6YCfIDE4W-aZrumAml0
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 50137
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5paw5Yqg5Z2h6auY6YCfIDE5W-aZrumAml0
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 50138
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5paw5Yqg5Z2h6auY6YCfIDIwW-aZrumAml0
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 50139
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: TE9MIOaJi-a4uOWKoOmAn1tWSVBd
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 30420
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 6aaZ5riv6auY6YCfMVtWSVBd
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 30520
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 6aaZ5riv6auY6YCfMltWSVBd
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 40155
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 6aaZ5riv6auY6YCfM1tWSVBd
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 30522
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 6aaZ5riv6auY6YCfNFtWSVBd
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 30523
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 6aaZ5riv6auY6YCfNVtWSVBd
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 30524
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 6aaZ5riv6auY6YCfNltWSVBd
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 30525
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 6aaZ5riv6auY6YCfN1tWSVBd
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 30526
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 6aaZ5riv6auY6YCfOFtWSVBd
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 30527
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 6aaZ5riv6auY6YCfOVtWSVBd
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 30528
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5paw5Yqg5Z2h6auY6YCfMVtWSVBd
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 20320
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5paw5Yqg5Z2h6auY6YCfMltWSVBd
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 30321
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5paw5Yqg5Z2h6auY6YCfM1tWSVBd
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 30322
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5paw5Yqg5Z2h6auY6YCfNFtWSVBd
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 30323
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5paw5Yqg5Z2h6auY6YCfNVtWSVBd
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 30324
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5Y-w5YyX6auY6YCfMVtWSVBd
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 30220
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5Y-w5YyX6auY6YCfMltWSVBd
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 30221
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5Y-w5YyX6auY6YCfM1tWSVBd
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 30222
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5Y-w5YyX6auY6YCfNFtWSVBd
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 30223
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5Y-w5YyX6auY6YCfNVtWSVBd
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 30224
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5pel5pys6auY6YCfIDFbVklQXQ
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 40320
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5pel5pys6auY6YCfIDJbVklQXQ
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 40321
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5pel5pys6auY6YCfIDNbVklQXQ
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 40322
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5pel5pys6auY6YCfIDRbVklQXQ
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 40323
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 5pel5pys6auY6YCfIDVbVklQXQ
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 40324
  server: dccm.ix2.edge.kunlunae.com
  type: ss
- cipher: chacha20
  name: 576O5Zu96auY6YCfW1ZJUF0
  password: mPQ5C9
  plugin: obfs
  plugin-opts:
    host: dccm.ix2.edge.kunlunae.com
    mode: tls1.2_ticket_auth
    tls: true
  port: 40220
  server: dccm.ix2.edge.kunlunae.com
  type: ss
proxy-groups:
- name: Proxy
  proxies:
  - 5pel5pys6auY6YCfIDFb5pmu6YCaXQ
  - 5pel5pys6auY6YCfIDJb5pmu6YCaXQ
  - 5pel5pys6auY6YCfIDNb5pmu6YCaXQ
  - 5pel5pys6auY6YCfIDRb5pmu6YCaXQ
  - 5pel5pys6auY6YCfIDVb5pmu6YCaXQ
  - 5pel5pys6auY6YCfIDZb5pmu6YCaXQ
  - 5pel5pys6auY6YCfIDdb5pmu6YCaXQ
  - 5pel5pys6auY6YCfIDhb5pmu6YCaXQ
  - 5pel5pys6auY6YCfIDlb5pmu6YCaXQ
  - 5pel5pys6auY6YCfIDEwW-aZrumAml0
  - 5pel5pys6auY6YCfIDExW-aZrumAml0
  - 5pel5pys6auY6YCfIDEyW-aZrumAml0
  - 5pel5pys6auY6YCfIDEzW-aZrumAml0
  - 5pel5pys6auY6YCfIDE0W-aZrumAml0
  - 5pel5pys6auY6YCfIDE1W-aZrumAml0
  - 5pel5pys6auY6YCfIDE2W-aZrumAml0
  - 5paw5Yqg5Z2h6auY6YCfIDE3W-aZrumAml0
  - 5paw5Yqg5Z2h6auY6YCfIDE4W-aZrumAml0
  - 5paw5Yqg5Z2h6auY6YCfIDE5W-aZrumAml0
  - 5paw5Yqg5Z2h6auY6YCfIDIwW-aZrumAml0
  - TE9MIOaJi-a4uOWKoOmAn1tWSVBd
  - 6aaZ5riv6auY6YCfMVtWSVBd
  - 6aaZ5riv6auY6YCfMltWSVBd
  - 6aaZ5riv6auY6YCfM1tWSVBd
  - 6aaZ5riv6auY6YCfNFtWSVBd
  - 6aaZ5riv6auY6YCfNVtWSVBd
  - 6aaZ5riv6auY6YCfNltWSVBd
  - 6aaZ5riv6auY6YCfN1tWSVBd
  - 6aaZ5riv6auY6YCfOFtWSVBd
  - 6aaZ5riv6auY6YCfOVtWSVBd
  - 5paw5Yqg5Z2h6auY6YCfMVtWSVBd
  - 5paw5Yqg5Z2h6auY6YCfMltWSVBd
  - 5paw5Yqg5Z2h6auY6YCfM1tWSVBd
  - 5paw5Yqg5Z2h6auY6YCfNFtWSVBd
  - 5paw5Yqg5Z2h6auY6YCfNVtWSVBd
  - 5Y-w5YyX6auY6YCfMVtWSVBd
  - 5Y-w5YyX6auY6YCfMltWSVBd
  - 5Y-w5YyX6auY6YCfM1tWSVBd
  - 5Y-w5YyX6auY6YCfNFtWSVBd
  - 5Y-w5YyX6auY6YCfNVtWSVBd
  - 5pel5pys6auY6YCfIDFbVklQXQ
  - 5pel5pys6auY6YCfIDJbVklQXQ
  - 5pel5pys6auY6YCfIDNbVklQXQ
  - 5pel5pys6auY6YCfIDRbVklQXQ
  - 5pel5pys6auY6YCfIDVbVklQXQ
  - 576O5Zu96auY6YCfW1ZJUF0
  type: select
proxy-provider: {}
rules: []
